#!/bin/sh
# Put the AOSP IMS stack into a LineageOS 22.2 tree for joan, in one go:
#
# 1. the Android 15 backport patches (aosp-ims/patches/, the same ones the
#    flashable zip is built from) onto the Android 17 ImsStack and ImsMedia
#    that local_manifests/aosp-ims.xml syncs;
# 2. the device change, device/0001-*.patch, onto device/lge/joan-common;
# 3. the per-carrier IMS config: what AOSP 17's CarrierConfig assets
#    changed (aosp-ims/carrier/aosp17-carrierconfig-ims.xml), under the
#    config LineageOS converts from Pixel carrier settings
#    (aosp-ims/carrier/lineage-pixel-ims.xml), then LG's own IMS settings
#    for the networks the Pixel data lacks (aosp-ims/carrier/lg-ims.xml),
#    spliced into joan-common's CarrierConfig vendor.xml as a commit of
#    its own. It is 7 MB of generated XML, so it is not in the patch;
# 4. the IMS, XCAP and emergency APNs LineageOS's list lacks, from the same
#    Pixel data (aosp-ims/carrier/lineage-pixel-apns.xml), as
#    vendor/apn/aosp-ims.xml in a commit of its own. vendor/apn serves every
#    device in the tree; the APNs are right for any of them.
# --no-carrier-data leaves out 3 and 4.
#
# Usage: upstream/aosp-ims/apply-patches.sh [--no-carrier-data] <LineageOS tree>
#
# Each patch becomes a commit in its project (git am), so `repo status`
# shows them. Safe to run again, for example after a `repo sync` reset the
# projects: a patch whose subject is already in the project's history is
# skipped, and the carrier data is committed only when it changes.
set -eu
KIT=$(cd "$(dirname "$0")/../.." && pwd)
CARRIER_DATA=1
if [ "${1:-}" = "--no-carrier-data" ]; then
    CARRIER_DATA=0
    shift
fi
TREE=$(cd "${1:?usage: $0 [--no-carrier-data] <LineageOS 22.2 tree>}" && pwd)

apply() { # apply <project path in the tree> <patch>...
    project=$1
    shift
    dir=$TREE/$project
    if ! git -C "$dir" rev-parse --git-dir >/dev/null 2>&1; then
        echo "$project: not synced. Add upstream/aosp-ims/local_manifests/aosp-ims.xml" \
             "to .repo/local_manifests/ and repo sync first." >&2
        exit 1
    fi
    for p in "$@"; do
        subject=$(git mailinfo /dev/null /dev/null < "$p" | sed -n 's/^Subject: //p')
        if git -C "$dir" log --format=%s -n 200 | grep -qxF "$subject"; then
            echo "$project: already applied: $subject"
            continue
        fi
        git -C "$dir" am -q --3way "$p"
        echo "$project: applied: $subject"
    done
}

apply packages/modules/ImsStack "$KIT"/aosp-ims/patches/ImsStack/*.patch
apply packages/modules/ImsMedia "$KIT"/aosp-ims/patches/ImsMedia/*.patch
apply device/lge/joan-common "$KIT"/upstream/aosp-ims/device/*.patch

[ "$CARRIER_DATA" = 1 ] || exit 0
DEV=$TREE/device/lge/joan-common
VX=overlay/packages/apps/CarrierConfig/res/xml/vendor.xml
python3 "$KIT/aosp-ims/tools/make-carrier-config.py" \
    "$KIT/ims-service/assets/carrier-id-map.json" \
    "$KIT/ims-service/assets/carrier-plmn-map.json" \
    "$KIT/aosp-ims/zip/java/com/android/imsstack/joan/CarrierImsGate.java" \
    "$TREE/packages/providers/TelephonyProvider/assets/latest_carrier_id/carrier_list.textpb" \
    --base "$KIT/aosp-ims/carrier/aosp17-carrierconfig-ims.xml" \
    --imported "$KIT/aosp-ims/carrier/lineage-pixel-ims.xml" \
    --fill "$KIT/aosp-ims/carrier/lg-ims.xml" --splice "$DEV/$VX"
if git -C "$DEV" diff --quiet -- "$VX"; then
    echo "device/lge/joan-common: per-carrier IMS config already in place"
else
    git -C "$DEV" commit -q -F - -- "$VX" <<'EOF'
joan-common: Import per-carrier IMS config

The IMS keys AOSP 17's CarrierConfig assets set differently from this
tree's (Android 15's), per carrier id: carriers added since, and changes
such as TIM's Ut and IPsec or Verizon's hold in IMS calls. Over them, the
IMS settings LineageOS ships for Pixels, which it converts from the
Pixel's CarrierSettings with lineage/scripts/carriersettings-extractor:
SIP, SMS over IMS, Ut/XCAP, emergency, video, RTT, ePDG and QNS settings
for some 570 carriers, filtered to the keys the AOSP IMS stack reads.
Then, for the networks that data has nothing for (in Russia, Latin
America, South Africa, Hong Kong and elsewhere), what LG's own IMS
settings for the V30 say about IPsec, USSD over IMS and the conference
factory. Placed after the aosp-ims ePDG blocks, so the carriers' own
addresses win, and before the every-SIM block, which keeps VoLTE and
Wi-Fi calling offered.

Generated by aosp-ims/tools/make-carrier-config.py (joan-volte-lineage).
EOF
    echo "device/lge/joan-common: committed the per-carrier IMS config"
fi

APN=$TREE/vendor/apn
if ! git -C "$APN" rev-parse --git-dir >/dev/null 2>&1; then
    echo "vendor/apn: not in the tree; the IMS APNs are left out" >&2
    exit 0
fi
python3 "$KIT/aosp-ims/tools/make-apns.py" "$KIT/aosp-ims/carrier/lineage-pixel-apns.xml" \
    --vendor-apn "$APN" | sed -n 1p
if [ -z "$(git -C "$APN" status --porcelain -- aosp-ims.xml)" ]; then
    echo "vendor/apn: IMS APNs already in place"
    exit 0
fi
git -C "$APN" add aosp-ims.xml
git -C "$APN" commit -q -F - -- aosp-ims.xml <<'EOF'
apn: Add the IMS, XCAP and emergency APNs this list lacks

From the Pixel carrier settings LineageOS converts with
lineage/scripts/carriersettings-extractor, for the networks whose SIMs
get no APN of the type from the country lists: IMS APNs other than the
"ims" Android falls back to (Verizon's MVNOs, among others), XCAP APNs
for Ut, and emergency APNs other than "sos". Each is added only at the
level the SIM's APNs already come from (its MVNO's rows, or its
MCC/MNC's), so no SIM loses an APN it has, and only for the type it
lacks. IMS and emergency APNs also allow IWLAN, for Wi-Fi calling.

Generated by aosp-ims/tools/make-apns.py (joan-volte-lineage).
EOF
echo "vendor/apn: committed the IMS APNs"
