#!/usr/bin/env python3
"""Write the Java classes aconfig would generate for a .aconfig file.

Outside the Android tree there is no aconfig. The generated API is small
(Flags with static accessors and FLAG_ names, the FeatureFlags interface,
FeatureFlagsImpl), and every flag here reads its declared default: off,
the release path upstream had before the flag, which is also the one the
Android 15 framework underneath was built for.

Usage: aconfig-stub.py <file.aconfig> <java out dir>
"""
import os
import re
import sys


def camel(name):
    head, *rest = name.split('_')
    return head + ''.join(p[:1].upper() + p[1:] for p in rest)


def main(src, out):
    text = open(src).read()
    package = re.search(r'^package:\s*"([^"]+)"', text, re.M).group(1)
    names = re.findall(r'flag\s*\{[^}]*?\bname:\s*"([^"]+)"', text, re.S)
    if not names:
        raise SystemExit(f'{src}: no flags')
    d = os.path.join(out, *package.split('.'))
    os.makedirs(d, exist_ok=True)
    hdr = f'package {package};\n\n/** Generated by aosp-ims/tools/aconfig-stub.py from {os.path.basename(src)}: every flag off. */\n'
    with open(os.path.join(d, 'FeatureFlags.java'), 'w') as f:
        f.write(hdr + 'public interface FeatureFlags {\n')
        f.writelines(f'    boolean {camel(n)}();\n' for n in names)
        f.write('}\n')
    with open(os.path.join(d, 'FeatureFlagsImpl.java'), 'w') as f:
        f.write(hdr + 'public final class FeatureFlagsImpl implements FeatureFlags {\n')
        f.writelines(f'    @Override public boolean {camel(n)}() {{ return false; }}\n' for n in names)
        f.write('}\n')
    with open(os.path.join(d, 'Flags.java'), 'w') as f:
        f.write(hdr + 'public final class Flags {\n')
        f.writelines(f'    public static final String FLAG_{n.upper()} = "{package}.{n}";\n' for n in names)
        f.writelines(f'    public static boolean {camel(n)}() {{ return false; }}\n' for n in names)
        f.write('}\n')
    print(f'{package}: {len(names)} flags, all off')


if __name__ == '__main__':
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    main(*sys.argv[1:])
