#!/usr/bin/env python3
"""Write the Java classes aconfig would generate for a .aconfig file.

Outside the Android tree there is no aconfig. The generated API is small
(Flags with static accessors and FLAG_ names, the FeatureFlags interface,
FeatureFlagsImpl). Each flag reads the value the Android 17 release gives
it: the flags named with --enable are on (build/release's cp1a config and
what it inherits set them ENABLED), every other flag is off, its declared
default.

Usage: aconfig-stub.py <file.aconfig> <java out dir> [--enable <flag>]...
"""
import os
import re
import sys


def camel(name):
    head, *rest = name.split('_')
    return head + ''.join(p[:1].upper() + p[1:] for p in rest)


def main(src, out, enabled=()):
    text = open(src).read()
    package = re.search(r'^package:\s*"([^"]+)"', text, re.M).group(1)
    names = re.findall(r'flag\s*\{[^}]*?\bname:\s*"([^"]+)"', text, re.S)
    if not names:
        raise SystemExit(f'{src}: no flags')
    unknown = set(enabled) - set(names)
    if unknown:
        raise SystemExit(f'{src}: no such flags: {sorted(unknown)}')
    on = {n: n in enabled for n in names}
    d = os.path.join(out, *package.split('.'))
    os.makedirs(d, exist_ok=True)
    hdr = (f'package {package};\n\n/** Generated by aosp-ims/tools/aconfig-stub.py from '
           f'{os.path.basename(src)}: the Android 17 release values. */\n')
    with open(os.path.join(d, 'FeatureFlags.java'), 'w') as f:
        f.write(hdr + 'public interface FeatureFlags {\n')
        f.writelines(f'    boolean {camel(n)}();\n' for n in names)
        f.write('}\n')
    with open(os.path.join(d, 'FeatureFlagsImpl.java'), 'w') as f:
        f.write(hdr + 'public final class FeatureFlagsImpl implements FeatureFlags {\n')
        f.writelines(f'    @Override public boolean {camel(n)}() {{ return {str(on[n]).lower()}; }}\n'
                     for n in names)
        f.write('}\n')
    with open(os.path.join(d, 'Flags.java'), 'w') as f:
        f.write(hdr + 'public final class Flags {\n')
        f.writelines(f'    public static final String FLAG_{n.upper()} = "{package}.{n}";\n' for n in names)
        f.writelines(f'    public static boolean {camel(n)}() {{ return {str(on[n]).lower()}; }}\n'
                     for n in names)
        f.write('}\n')
    print(f'{package}: {len(names)} flags, on: {sorted(n for n in names if on[n]) or "none"}')


if __name__ == '__main__':
    args = sys.argv[1:]
    enabled = []
    while len(args) > 2 and args[-2] == '--enable':
        enabled.append(args[-1])
        args = args[:-2]
    if len(args) != 2 or '--enable' in args:
        raise SystemExit(__doc__)
    main(*args, enabled=enabled)
