#!/usr/bin/env python3
"""Import the APN list LineageOS converts from the Pixel carrier settings.

LineageOS's generic APN list (vendor/apn, what joan ships) has IMS APNs for
about 200 networks. The Pixel carrier settings LineageOS converts for its
Pixel builds, with its own carriersettings-extractor, have them for about
1400, and XCAP (Ut) and emergency APNs for hundreds more. Android 15 falls
back to an IMS APN named "ims" and an emergency APN named "sos" when a SIM
has none, so the networks whose APNs are named otherwise (Verizon's MVNOs,
among others), and every XCAP APN, are missing on joan.

This runs the converter over the pinned CarrierSettings and writes its APN
list whole, one <apn> per line, in the converter's attribute order. Nothing
is filtered here: which of these a phone needs depends on the APNs the ROM
already has, which make-apns.py works out (at build time for a source
build, at run time on the phone for the zip).

Usage: import-carrier-apns.py <carriersettings-extractor dir>
           <CarrierSettings dir> <source description> <out.xml>
"""
import os
import subprocess
import sys
import tempfile
import xml.etree.ElementTree as ET
from xml.sax.saxutils import escape, quoteattr

TYPES = ('ims', 'xcap', 'emergency')


def main(extractor_dir, pb_dir, source, out):
    extractor = os.path.join(os.path.abspath(extractor_dir), 'carriersettings_extractor.py')
    with tempfile.TemporaryDirectory() as tmp:
        # The converter writes vendor.xml too; only its APN list is used.
        subprocess.run([sys.executable, extractor, '-i', os.path.abspath(pb_dir),
                        '-a', tmp, '-v', tmp],
                       check=True, cwd=os.path.dirname(extractor),
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        apns = ET.parse(os.path.join(tmp, 'apns-conf.xml')).getroot().findall('apn')

    networks = {t: set() for t in TYPES}
    for a in apns:
        types = {t.strip() for t in (a.get('type') or '').split(',')}
        for t in TYPES:
            if t in types or '*' in types:
                networks[t].add((a.get('mcc'), a.get('mnc'), a.get('mvno_type'),
                                 a.get('mvno_match_data')))
    plmns = {(a.get('mcc'), a.get('mnc')) for a in apns}
    lines = ['<?xml version="1.0" encoding="utf-8"?>',
             '<!-- aosp-ims: the APNs of the Pixel CarrierSettings, as LineageOS converts them.',
             f'     {escape(source)}',
             f'     {len(apns)} APNs on {len(plmns)} PLMNs; IMS APNs for '
             f'{len(networks["ims"])} networks, XCAP {len(networks["xcap"])}, '
             f'emergency {len(networks["emergency"])}.',
             '     Generated by aosp-ims/tools/import-carrier-apns.py. -->',
             '<apns version="8">']
    for a in apns:
        attrs = ' '.join(f'{k}={quoteattr(v)}' for k, v in a.attrib.items())
        lines.append(f'  <apn {attrs}/>')
    lines.append('</apns>')
    with open(out, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')
    print(f'{out}: {len(apns)} APNs, {len(plmns)} PLMNs; networks with IMS '
          f'{len(networks["ims"])}, XCAP {len(networks["xcap"])}, '
          f'emergency {len(networks["emergency"])}')


if __name__ == '__main__':
    if len(sys.argv) != 5:
        raise SystemExit(__doc__)
    main(*sys.argv[1:])
