#!/usr/bin/env python3
"""The zip's carrier gate as CarrierConfig vendor.xml blocks, for a ROM
built from source with the AOSP IMS stack (upstream/AOSP-IMS.md).

The flashable zip cannot change CarrierConfig, so CarrierImsGate overrides
carrier config at run time from inside ImsStack. A device tree can say the
same thing statically, in the vendor.xml overlay CarrierConfig already
reads. Same data, same decisions:

- VoLTE is offered for every SIM, with the Enhanced 4G LTE toggle visible
  and editable.
- Wi-Fi calling is offered where the SIM's LG profile shipped VoWiFi. A
  SIM resolves to a profile by Android carrier id, then by PLMN, as the
  gate does. One block per carrier id and per PLMN, PLMN blocks first:
  CarrierConfig merges every matching block in document order, so a
  carrier id block overrides its PLMN's block, as the gate prefers the
  carrier id.
- The ePDG address is set for the operators whose ePDG is not the 3GPP
  default name. Read from CarrierImsGate.java, so the two cannot drift.

Only carrier ids the gate can match get a block. The gate reads
TelephonyManager.getSimCarrierId(); a vendor.xml cid filter also matches
the specific carrier id, so ids that are specific (they have a parent in
carrier_list.textpb) are left out. tests/check-carrier-config.py checks
the result against the gate's rules for every carrier id and PLMN.

One difference, by design: vendor.xml overrides the carrier's own config
where the gate only fills in what is missing. Android 15's CarrierConfig
assets set no ePDG address and never disable Wi-Fi calling for a carrier
listed here, so the outcome is the same on LineageOS 22.2.

Usage:
  make-carrier-config.py <carrier-id-map.json> <carrier-plmn-map.json>
      <wfc-profiles.json> <CarrierImsGate.java> <carrier_list.textpb>
      [--splice <vendor.xml>]

Prints the blocks. With --splice, writes them into the given vendor.xml
between the aosp-ims markers, replacing an earlier copy, or before
</carrier_config_list> the first time.
"""
import json
import re
import sys
from xml.sax.saxutils import escape, quoteattr

BEGIN = '    <!-- aosp-ims-begin: generated by aosp-ims/tools/make-carrier-config.py -->'
END = '    <!-- aosp-ims-end -->'

KEY_VOLTE = 'carrier_volte_available_bool'
KEY_HIDE_4G = 'hide_enhanced_4g_lte_bool'
KEY_EDITABLE_4G = 'editable_enhanced_4g_lte_bool'
KEY_WFC = 'carrier_wfc_ims_available_bool'
KEY_EPDG_STATIC = 'iwlan.epdg_static_address_string'
KEY_EPDG_PRIORITY = 'iwlan.epdg_address_priority_int_array'
EPDG_ADDRESS_STATIC, EPDG_ADDRESS_PLMN = 0, 1


def operator_of(profile):
    """"OP.CC" of an LG profile key such as TMO.US.NAO (CarrierImsGate.operatorOf)."""
    parts = profile.split('.')
    return parts[0] + '.' + parts[1] if len(parts) >= 2 else profile


def is_wfc(profile, wfc):
    return profile is not None and (profile in wfc or operator_of(profile) in wfc)


def epdg_map(gate_java):
    """EPDG_BY_OPERATOR, read out of CarrierImsGate.java."""
    src = open(gate_java, encoding='utf-8').read()
    m = re.search(r'EPDG_BY_OPERATOR\s*=\s*Map\.of\((.*?)\);', src, re.S)
    if not m:
        raise SystemExit(f'{gate_java}: EPDG_BY_OPERATOR not found')
    vals = re.findall(r'"([^"]*)"', m.group(1))
    if not vals or len(vals) % 2:
        raise SystemExit(f'{gate_java}: EPDG_BY_OPERATOR is not key/value pairs')
    return dict(zip(vals[0::2], vals[1::2]))


def carrier_list(textpb):
    """{carrier id: (name, parent id or None)} from carrier_list.textpb."""
    out = {}
    for block in re.split(r'\ncarrier_id \{', open(textpb, encoding='utf-8').read()):
        m = re.search(r'canonical_id: (\d+)', block)
        if not m:
            continue
        name = re.search(r'carrier_name: "([^"]*)"', block)
        parent = re.search(r'parent_canonical_id: (\d+)', block)
        out[int(m.group(1))] = (name.group(1) if name else '',
                                int(parent.group(1)) if parent else None)
    return out


def load(id_map, plmn_map, wfc_json, gate_java, textpb):
    return (json.load(open(id_map)), json.load(open(plmn_map)),
            set(json.load(open(wfc_json))['profiles']), epdg_map(gate_java),
            carrier_list(textpb))


def wfc_values(profile, epdg):
    """The Wi-Fi calling values the gate applies for one profile."""
    vals = [(KEY_WFC, True)]
    addr = epdg.get(operator_of(profile))
    if addr:
        vals.append((KEY_EPDG_STATIC, addr))
        vals.append((KEY_EPDG_PRIORITY, [EPDG_ADDRESS_STATIC, EPDG_ADDRESS_PLMN]))
    return vals


def blocks(ids, plmns, wfc, epdg, carriers):
    """[(filter attrs, comment, [(key, value)])] in document order."""
    out = [({}, 'VoLTE for every SIM, with the toggle visible and editable',
            [(KEY_VOLTE, True), (KEY_HIDE_4G, False), (KEY_EDITABLE_4G, True)])]
    for plmn in sorted(plmns):
        profile = plmns[plmn]
        if is_wfc(profile, wfc):
            out.append(({'mcc': plmn[:3], 'mnc': plmn[3:]}, profile,
                        wfc_values(profile, epdg)))
    for cid in sorted(ids, key=int):
        profile = ids[cid]
        name, parent = carriers.get(int(cid), ('', None))
        if parent is not None or not is_wfc(profile, wfc):
            continue
        attrs = {'cid': cid}
        if name:
            attrs['name'] = name
        out.append((attrs, profile, wfc_values(profile, epdg)))
    return out


def render(bl):
    lines = [BEGIN,
             '    <!-- AOSP IMS stack (ImsStack): VoLTE for every carrier; Wi-Fi calling',
             '         where the SIM\'s LG profile shipped VoWiFi, by carrier id, then PLMN.',
             '         Same rules as the flashable zip\'s CarrierImsGate. -->']
    for attrs, comment, values in bl:
        head = ''.join(f' {k}={quoteattr(v)}' for k, v in attrs.items())
        lines.append(f'    <carrier_config{head}> <!-- {escape(comment)} -->')
        for key, value in values:
            if isinstance(value, bool):
                lines.append(f'        <boolean name="{key}" value="{str(value).lower()}" />')
            elif isinstance(value, list):
                lines.append(f'        <int-array name="{key}" num="{len(value)}">')
                lines += [f'            <item value="{v}" />' for v in value]
                lines.append('        </int-array>')
            else:
                lines.append(f'        <string name="{key}">{escape(value)}</string>')
        lines.append('    </carrier_config>')
    lines.append(END)
    return '\n'.join(lines) + '\n'


def splice(vendor_xml, text):
    doc = open(vendor_xml, encoding='utf-8').read()
    if BEGIN in doc:
        start = doc.index(BEGIN)
        end = doc.index(END, start) + len(END) + 1
        doc = doc[:start] + text + doc[end:]
    else:
        close = doc.rindex('</carrier_config_list>')
        doc = doc[:close].rstrip('\n') + '\n\n' + text + doc[close:]
    open(vendor_xml, 'w', encoding='utf-8').write(doc)


def main(argv):
    target = None
    if '--splice' in argv:
        i = argv.index('--splice')
        target = argv[i + 1]
        argv = argv[:i] + argv[i + 2:]
    if len(argv) != 5:
        raise SystemExit(__doc__)
    ids, plmns, wfc, epdg, carriers = load(*argv)
    text = render(blocks(ids, plmns, wfc, epdg, carriers))
    if target:
        splice(target, text)
        print(f'{target}: {text.count("<carrier_config")} carrier_config blocks')
    else:
        sys.stdout.write(text)


if __name__ == '__main__':
    main(sys.argv[1:])
