#!/usr/bin/env python3
"""The zip's carrier data as CarrierConfig vendor.xml blocks.

The flashable zip and the repacked ROM ship ImsStackCarrierConfigOverlay,
a runtime resource overlay replacing the CarrierConfig app's
res/xml/vendor.xml wholesale (a device tree says the same thing statically
in its own vendor.xml; same region, same tool). The overlay must carry the
ROM's own vendor.xml content -- an RRO replaces the whole resource -- so
the file is assembled in three layers, in document order:

- the ROM's vendor.xml (aosp-ims/carrier/joan-common-vendor-base.xml for
  joan), untouched;
- the region this tool writes between the aosp-ims markers:
  1. our ePDG blocks: addresses for the operators whose ePDG is not the
     3GPP default name, read from CarrierImsGate.java so the gate and the
     file cannot drift. One block per carrier id and per PLMN, PLMN
     blocks first: CarrierConfig merges every matching block in document
     order, so a carrier id block overrides its PLMN's block, as the gate
     prefers the carrier id.
  2. the imported blocks (aosp-ims/carrier/lineage-pixel-ims.xml): the
     IMS keys LineageOS converts from Google's Pixel CarrierSettings,
     with the converter's own filters (mcc/mnc, gid1, spn, imsi). Their
     ePDG addresses are authoritative: where Google's data and our table
     disagree, Google's wins, which is why ours come first.
  3. the filterless block last, so it wins for its keys: VoLTE and
     Wi-Fi calling available for every SIM, both toggles visible and
     editable, and IMS stays user-turnoff-able.

Only carrier ids the gate can match get a block of their own. The gate
reads TelephonyManager.getSimCarrierId(); a vendor.xml cid filter also
matches the specific carrier id, so ids that are specific (they have a
parent in carrier_list.textpb) are left out.
tests/check-carrier-config.py checks the result against the gate's rules
for every carrier id and PLMN.

Usage:
  make-carrier-config.py <carrier-id-map.json> <carrier-plmn-map.json>
      <CarrierImsGate.java> <carrier_list.textpb> [--import <import.xml>]
      [--splice <vendor.xml>]

Prints the region. With --splice, writes it into the given vendor.xml
between the aosp-ims markers, replacing an earlier copy, or before
</carrier_config_list> the first time.
"""
import json
import re
import sys
from xml.sax.saxutils import escape, quoteattr

BEGIN = '    <!-- aosp-ims-begin: generated by aosp-ims/tools/make-carrier-config.py -->'
END = '    <!-- aosp-ims-end -->'

KEY_VOLTE = 'carrier_volte_available_bool'
KEY_HIDE_4G = 'hide_enhanced_4g_lte_bool'
KEY_EDITABLE_4G = 'editable_enhanced_4g_lte_bool'
KEY_WFC = 'carrier_wfc_ims_available_bool'
KEY_TURNOFF = 'carrier_allow_turnoff_ims_bool'
KEY_EPDG_STATIC = 'iwlan.epdg_static_address_string'
KEY_EPDG_PRIORITY = 'iwlan.epdg_address_priority_int_array'
EPDG_ADDRESS_STATIC, EPDG_ADDRESS_PLMN = 0, 1

FINAL = [
    (KEY_VOLTE, True),
    (KEY_WFC, True),
    (KEY_HIDE_4G, False),
    (KEY_EDITABLE_4G, True),
    (KEY_TURNOFF, True),
]


def operator_of(profile):
    """"OP.CC" of an LG profile key such as TMO.US.NAO (CarrierImsGate.operatorOf)."""
    parts = profile.split('.')
    return parts[0] + '.' + parts[1] if len(parts) >= 2 else profile


def epdg_map(gate_java):
    """EPDG_BY_OPERATOR, read out of CarrierImsGate.java."""
    src = open(gate_java, encoding='utf-8').read()
    m = re.search(r'EPDG_BY_OPERATOR\s*=\s*Map\.of\((.*?)\);', src, re.S)
    if not m:
        raise SystemExit(f'{gate_java}: EPDG_BY_OPERATOR not found')
    vals = re.findall(r'"([^"]*)"', m.group(1))
    if not vals or len(vals) % 2:
        raise SystemExit(f'{gate_java}: EPDG_BY_OPERATOR is not key/value pairs')
    return dict(zip(vals[0::2], vals[1::2]))


def carrier_list(textpb):
    """{carrier id: (name, parent id or None)} from carrier_list.textpb."""
    out = {}
    for block in re.split(r'\ncarrier_id \{', open(textpb, encoding='utf-8').read()):
        m = re.search(r'canonical_id: (\d+)', block)
        if not m:
            continue
        name = re.search(r'carrier_name: "([^"]*)"', block)
        parent = re.search(r'parent_canonical_id: (\d+)', block)
        out[int(m.group(1))] = (name.group(1) if name else '',
                                int(parent.group(1)) if parent else None)
    return out


def load(id_map, plmn_map, gate_java, textpb):
    return (json.load(open(id_map)), json.load(open(plmn_map)),
            epdg_map(gate_java), carrier_list(textpb))


def epdg_values(addr):
    """The ePDG values the gate applies for one profile."""
    return [(KEY_EPDG_STATIC, addr),
            (KEY_EPDG_PRIORITY, [EPDG_ADDRESS_STATIC, EPDG_ADDRESS_PLMN])]


def blocks(ids, plmns, epdg, carriers):
    """[(filter attrs, comment, [(key, value)])] for our own rules."""
    out = []
    for plmn in sorted(plmns):
        addr = epdg.get(operator_of(plmns[plmn]))
        if addr:
            out.append(({'mcc': plmn[:3], 'mnc': plmn[3:]}, plmns[plmn],
                        epdg_values(addr)))
    for cid in sorted(ids, key=int):
        profile = ids[cid]
        addr = epdg.get(operator_of(profile))
        name, parent = carriers.get(int(cid), ('', None))
        if parent is not None or not addr:
            continue
        attrs = {'cid': cid}
        if name:
            attrs['name'] = name
        out.append((attrs, profile, epdg_values(addr)))
    return out


def imported(path):
    """[(filter attrs, comment, [child lines])] read back from the
    importer's output (import-carrier-settings.py), passed through
    verbatim: its blocks are already rendered CarrierConfig XML."""
    out = []
    for m in re.finditer(
            r'    <!-- (.+?) -->\n(    <carrier_config[^\n]*>\n(?:.*?\n)?    </carrier_config>)',
            open(path, encoding='utf-8').read(), re.S):
        el = m.group(2)
        head = el[:el.index('>')]
        attrs = dict(re.findall(r'([a-z0-9_]+)="([^"]*)"', head))
        children = el[el.index('>') + 1:el.rindex('</carrier_config>')].strip('\n')
        out.append((attrs, m.group(1), children.split('\n')))
    if not out:
        raise SystemExit(f'{path}: no imported blocks found')
    return out


def render(bl, imp):
    lines = [BEGIN,
             '    <!-- AOSP IMS stack (ImsStack): ePDG overrides for the operators whose',
             '         ePDG is not the 3GPP default name (CarrierImsGate\'s table); then',
             '         the IMS carrier data converted from Google\'s Pixel CarrierSettings',
             '         (aosp-ims/carrier/lineage-pixel-ims.xml), whose addresses win; then',
             '         VoLTE and Wi-Fi calling for every SIM, both toggles usable. Same',
             '         rules as the flashable zip\'s CarrierImsGate. -->']
    for attrs, comment, values in bl:
        head = ''.join(f' {k}={quoteattr(v)}' for k, v in attrs.items())
        lines.append(f'    <carrier_config{head}> <!-- {escape(comment)} -->')
        for key, value in values:
            if isinstance(value, bool):
                lines.append(f'        <boolean name="{key}" value="{str(value).lower()}" />')
            elif isinstance(value, list):
                lines.append(f'        <int-array name="{key}" num="{len(value)}">')
                lines += [f'            <item value="{v}" />' for v in value]
                lines.append('        </int-array>')
            else:
                lines.append(f'        <string name="{key}">{escape(value)}</string>')
        lines.append('    </carrier_config>')
    for attrs, comment, children in imp:
        head = ''.join(f' {k}={quoteattr(v)}' for k, v in attrs.items())
        lines.append(f'    <!-- {escape(comment)} -->')
        lines.append(f'    <carrier_config{head}>')
        lines += children
        lines.append('    </carrier_config>')
    lines.append('    <carrier_config> <!-- offered for every SIM -->')
    for key, value in FINAL:
        lines.append(f'        <boolean name="{key}" value="{str(value).lower()}" />')
    lines.append('    </carrier_config>')
    lines.append(END)
    return '\n'.join(lines) + '\n'


def region_text(ids, plmns, epdg, carriers, import_path):
    bl = blocks(ids, plmns, epdg, carriers)
    imp = imported(import_path) if import_path else []
    return render(bl, imp)


def splice(vendor_xml, text):
    doc = open(vendor_xml, encoding='utf-8').read()
    if BEGIN in doc:
        start = doc.index(BEGIN)
        end = doc.index(END, start) + len(END) + 1
        doc = doc[:start] + text + doc[end:]
    else:
        close = doc.rindex('</carrier_config_list>')
        doc = doc[:close].rstrip('\n') + '\n\n' + text + doc[close:]
    open(vendor_xml, 'w', encoding='utf-8').write(doc)


def main(argv):
    target = import_path = None
    if '--splice' in argv:
        i = argv.index('--splice')
        target = argv[i + 1]
        argv = argv[:i] + argv[i + 2:]
    if '--import' in argv:
        i = argv.index('--import')
        import_path = argv[i + 1]
        argv = argv[:i] + argv[i + 2:]
    if len(argv) != 4:
        raise SystemExit(__doc__)
    ids, plmns, epdg, carriers = load(*argv)
    text = region_text(ids, plmns, epdg, carriers, import_path)
    if target:
        splice(target, text)
        print(f'{target}: {text.count("<carrier_config")} carrier_config blocks')
    else:
        sys.stdout.write(text)


if __name__ == '__main__':
    main(sys.argv[1:])
