#!/usr/bin/env python3
"""Generate the AOSP IMS zip's installer and uninstaller from joan's.

joan's scripts/update-binary (installer v8) is the one that flashes cleanly
across LineageOS-based ROMs: it mounts dynamic partitions the way alpha67
did, writes every file atomically, checks free space before touching
anything, orders the privapp allowlist before the apk, and stamps the
package cache so PackageManager rereads what changed (the fix for the
post-alpha67 bootloop). Rather than fork that logic, this rewrites the
names of what it installs and adds what the AOSP stack needs: the
sysconfig file, hints naming this stack's own launcher entry, and one
of two joan policies. update-binary (fresh flash) refuses a phone that has
joan, before writing anything; update-binary-migrate removes joan's stack,
which this one replaces, keeping the files both share.

Every rewrite must match the expected number of times, so a change to the
joan scripts fails this build instead of producing a half-renamed
installer.

Usage: make-installer.py <scripts dir> <out dir>
"""
import os
import sys

BANNER = """#
# GENERATED by aosp-ims/tools/make-installer.py from joan's
# scripts/{src}. Edit that file or the generator, not this one.
# Installs AOSP ImsStack + ImsMedia (com.android.imsstack) in place of joan.
"""

# (old, new, how many times old must occur)
INSTALL = [
    ('ui_print "joan-volte v7.5: ImsService apk (SAR/verity-safe installer)"\n',
     'ui_print "AOSP IMS (Android 17 ImsStack + ImsMedia) for LineageOS 22.2, joan installer"\n', 1),
    ('JoanImsPhoneDefault.apk', 'ImsStackPhoneOverlay.apk', 2),
    ('JoanFwVolte.apk', 'ImsStackFrameworkOverlay.apk', 2),
    ('joan-ims-rro.apk', 'ImsStackPhoneOverlay.apk', 3),
    ('joan-fw-volte.apk', 'ImsStackFrameworkOverlay.apk', 3),
    ('joan-ims.apk', 'ImsStack.apk', 3),
    ('JoanIms', 'ImsStack', 11),
    ('org.joan.ims.xml', 'com.android.imsstack.xml', 10),
    # CallPermissionsActivity: in the app drawer while the microphone is
    # missing. Wi-Fi calling's IPsec app-op has no dialog, so adb stays.
    ('    ui_print "    otherwise open \\"joan IMS\\" once from the launcher"\n',
     '    ui_print "    otherwise open \\"Calling permissions\\" in the app drawer"\n', 1),
    ('    warn "  skipped the default grants; open \\"joan IMS\\" once from the launcher"\n',
     '    warn "  skipped the default grants; open \\"Calling permissions\\" in the app drawer"\n', 1),
    ('ui_print "If a call\'s far end hears nothing, grant the microphone:"\n',
     'ui_print "If \\"Calling permissions\\" appears in the app drawer, open it:"\n', 1),
    ('ui_print "  open \\"joan IMS\\" once, or: adb shell pm grant org.joan.ims android.permission.RECORD_AUDIO"\n',
     'ui_print "  calls need the microphone. Wi-Fi calling: run grant-permissions.sh"\n'
     'ui_print "  (in this zip) once over adb"\n', 1),
    # Free space as a write can use it. toybox df (recovery's) counts ext4's
    # reserved clusters as free -- up to 16 MB -- so on a nearly full
    # partition the check passed and the write failed part way, after
    # system was already written. statfs's f_bavail leaves them out.
    ('''free_kb() {
  fk=$(df -k "$1" 2>/dev/null | tail -1 | tr -s " " | cut -d" " -f4)
''', '''free_kb() {
  fk=$(stat -f -c "%a %S" "$1" 2>/dev/null)
  fk_a=${fk% *}
  fk_s=${fk#* }
  case "$fk_a:$fk_s" in
    *[!0-9:]*|:*|*:) ;;
    *) if [ "$fk_s" -ge 1024 ]; then echo $((fk_a * (fk_s / 1024))); return 0; fi ;;
  esac
  fk=$(df -k "$1" 2>/dev/null | tail -1 | tr -s " " | cut -d" " -f4)
''', 1),
    # Space: the sysconfig file is installed too.
    ('  "$TMP/etc/default-permissions/com.android.imsstack.xml")\n',
     '  "$TMP/etc/default-permissions/com.android.imsstack.xml" \\\n'
     '  "$TMP/etc/sysconfig/com.android.imsstack.xml" \\\n'
     '  "$TMP/app/Iwlan.apk" "$TMP/app/QualifiedNetworksService.apk" \\\n'
     '  "$TMP/etc/permissions/com.google.android.iwlan.xml" \\\n'
     '  "$TMP/etc/permissions/com.android.telephony.qns.xml" \\\n'
     '  "$TMP/etc/sysconfig/com.google.android.iwlan.xml")\n', 1),
    # After the allowlist: power-save and data-saver exemptions, so an
    # incoming call reaches the stack while the phone sleeps.
    ('ui_print "Installing ImsService priv-app"\n',
     '''if [ -f "$TMP/etc/sysconfig/com.android.imsstack.xml" ]; then
  mkdir -p "$SYS/etc/sysconfig" 2>/dev/null
  copy_file "$TMP/etc/sysconfig/com.android.imsstack.xml" \\
    "$SYS/etc/sysconfig/com.android.imsstack.xml" 644 u:object_r:system_file:s0
fi
# VoWiFi: allowlists (and IWLAN's power-save exemption) before their apks.
for f in com.google.android.iwlan com.android.telephony.qns; do
  if [ -f "$TMP/etc/permissions/$f.xml" ]; then
    copy_file "$TMP/etc/permissions/$f.xml" "$SYS/etc/permissions/$f.xml" 644 u:object_r:system_file:s0
  fi
done
if [ -f "$TMP/etc/sysconfig/com.google.android.iwlan.xml" ]; then
  copy_file "$TMP/etc/sysconfig/com.google.android.iwlan.xml" \\
    "$SYS/etc/sysconfig/com.google.android.iwlan.xml" 644 u:object_r:system_file:s0
fi
ui_print "Installing ImsService priv-app (AOSP ImsStack + ImsMedia)"
''', 1),
    # The stack hands incoming calls to the framework's ImsPhoneCallTracker,
    # which LineageOS gates on ro.telephony.block_binder_thread_on_incoming_
    # calls; joan's tree sets it false for the modem IMS this replaces, and
    # with it false the framework returns no listener for any incoming call,
    # so the stack answers 480 and the phone never rings. Flip that one line
    # (through copy_file: atomic, mode and label kept) and leave a marker for
    # the uninstaller, which flips it back. Nothing else in build.prop is
    # touched, and no copy of it is kept that a ROM update could outdate.
    ('ui_print "Installing ImsService priv-app (AOSP ImsStack + ImsMedia)"\n',
     '''ui_print "Installing ImsService priv-app (AOSP ImsStack + ImsMedia)"
BP="$SYS/build.prop"
IC=ro.telephony.block_binder_thread_on_incoming_calls
if [ -f "$BP" ] && grep -q "^$IC=false\$" "$BP"; then
  sed "s/^$IC=false\$/$IC=true/" "$BP" > "$TMP/build.prop.aosp-ims"
  copy_file "$TMP/build.prop.aosp-ims" "$BP" 644 u:object_r:system_file:s0
  echo "$IC=false" > "$SYS/etc/aosp-ims-incoming-calls.flipped"
  chmod 644 "$SYS/etc/aosp-ims-incoming-calls.flipped" 2>/dev/null || true
  chcon u:object_r:system_file:s0 "$SYS/etc/aosp-ims-incoming-calls.flipped" 2>/dev/null || true
  ui_print "  build.prop: framework incoming-call handling on"
fi
''', 1),
    # After ImsStack: the VoWiFi apps, IWLAN (ePDG tunnel) and QNS
    # (LTE <-> Wi-Fi transport choice).
    ('copy_file "$TMP/app/ImsStack.apk" "$SYS/priv-app/ImsStack/ImsStack.apk" 644 u:object_r:system_file:s0\n',
     '''copy_file "$TMP/app/ImsStack.apk" "$SYS/priv-app/ImsStack/ImsStack.apk" 644 u:object_r:system_file:s0
for wa in Iwlan QualifiedNetworksService; do
  [ -f "$TMP/app/$wa.apk" ] || continue
  ui_print "Installing VoWiFi priv-app $wa"
  mkdir -p "$SYS/priv-app/$wa"
  chmod 755 "$SYS/priv-app/$wa" 2>/dev/null || true
  chcon u:object_r:system_file:s0 "$SYS/priv-app/$wa" 2>/dev/null || true
  copy_file "$TMP/app/$wa.apk" "$SYS/priv-app/$wa/$wa.apk" 644 u:object_r:system_file:s0
done
''', 1),
    # Temp files and package-cache stamps cover the VoWiFi apps too.
    ('rm -f "$SYS/priv-app/ImsStack/"*.joan-new \\\n',
     'rm -f "$SYS/priv-app/ImsStack/"*.joan-new \\\n'
     '      "$SYS/priv-app/Iwlan/"*.joan-new "$SYS/priv-app/QualifiedNetworksService/"*.joan-new \\\n'
     '      "$SYS/etc/sysconfig/"*.joan-new \\\n', 1),
    ('  "$PRODMNT/overlay/ImsStackPhoneOverlay.apk" "$PRODMNT/overlay/ImsStackFrameworkOverlay.apk"\n',
     '  "$PRODMNT/overlay/ImsStackPhoneOverlay.apk" "$PRODMNT/overlay/ImsStackFrameworkOverlay.apk" \\\n'
     '  "$SYS/priv-app/Iwlan/Iwlan.apk" "$SYS/priv-app/Iwlan" \\\n'
     '  "$SYS/priv-app/QualifiedNetworksService/QualifiedNetworksService.apk" \\\n'
     '  "$SYS/priv-app/QualifiedNetworksService"\n', 1),
]

MIGRATE = [
    # Before the allowlist: joan's stack goes, this one replaces it.
    ('# The allowlist goes down FIRST, and the apk second.\n',
     '''# --- joan's own IMS stack is replaced ------------------------------------
# Two ImsServices for one SIM would fight over the registration, and only
# one device default can win, so joan's goes. The files it shares with
# this package (the IMS feature xml and its ownership marker, the merged
# APN list and its backup) stay, and this package's uninstaller handles
# them the same way.
if [ -d "$SYS/priv-app/JoanIms" ] || [ -f "$PRODMNT/overlay/JoanImsPhoneDefault.apk" ]; then
  ui_print "Removing the joan IMS stack (this package replaces it)"
  rm -rf "$SYS/priv-app/JoanIms"
  rm -f "$SYS/etc/permissions/org.joan.ims.xml" \\
        "$SYS/etc/default-permissions/org.joan.ims.xml" \\
        "$PRODMNT/overlay/JoanImsPhoneDefault.apk" \\
        "$PRODMNT/overlay/JoanFwVolte.apk"
fi

# The allowlist goes down FIRST, and the apk second.
''', 1),
]

FRESH = [
    # Before anything is written: a phone with joan gets the migration zip.
    ('# --- Space, before anything is written',
     '''# --- Fresh install only ----------------------------------------------------
# This zip is for phones without joan's IMS stack. Two stacks would
# register the same SIM and fight over it, so a phone that has joan needs
# the migration zip, which removes joan first. Checked before anything is
# written.
if [ -d "$SYS/priv-app/JoanIms" ] || [ -f "$SYS/etc/permissions/org.joan.ims.xml" ] \\
    || [ -f "$PRODMNT/overlay/JoanImsPhoneDefault.apk" ]; then
  error "joan's IMS stack is installed. Flash the aosp-ims ...-migrate-from-joan.zip instead: it removes joan, then installs this. Nothing was changed."
fi

# --- Space, before anything is written''', 1),
]

UNINSTALL = [
    ('ui_print "joan-volte uninstall: removing ImsService"\n',
     'ui_print "AOSP IMS uninstall: removing com.android.imsstack"\n', 1),
    ('rm -rf "$SYS/priv-app/JoanIms"\n', 'rm -rf "$SYS/priv-app/ImsStack"\n', 1),
    ('rm -f "$SYS/etc/permissions/org.joan.ims.xml" "$SYS/etc/permissions/"*.joan-new\n',
     'rm -f "$SYS/etc/permissions/com.android.imsstack.xml" "$SYS/etc/permissions/"*.joan-new\n'
     'rm -f "$SYS/etc/sysconfig/com.android.imsstack.xml"\n', 1),
    ('rm -f "$SYS/etc/default-permissions/org.joan.ims.xml"\n',
     'rm -f "$SYS/etc/default-permissions/com.android.imsstack.xml"\n'
     'rm -rf "$SYS/priv-app/Iwlan" "$SYS/priv-app/QualifiedNetworksService"\n'
     'rm -f "$SYS/etc/permissions/com.google.android.iwlan.xml" \\\n'
     '      "$SYS/etc/permissions/com.android.telephony.qns.xml" \\\n'
     '      "$SYS/etc/sysconfig/com.google.android.iwlan.xml" "$SYS/etc/sysconfig/"*.joan-new\n', 1),
    ('JoanIms + leftovers removed', 'ImsStack + leftovers removed', 1),
    # Undo the incoming-call flip, only where the installer made it, one
    # line, written beside build.prop and renamed over it.
    ('ui_print "  /system: ImsStack + leftovers removed (or absent)"\n',
     '''ui_print "  /system: ImsStack + leftovers removed (or absent)"
BP="$SYS/build.prop"
IC=ro.telephony.block_binder_thread_on_incoming_calls
if [ -f "$SYS/etc/aosp-ims-incoming-calls.flipped" ]; then
  if grep -q "^$IC=true\$" "$BP" 2>/dev/null \
      && sed "s/^$IC=true\$/$IC=false/" "$BP" > "$BP.aosp-ims-new" \
      && chmod 644 "$BP.aosp-ims-new" \
      && { chcon u:object_r:system_file:s0 "$BP.aosp-ims-new" 2>/dev/null; true; } \
      && mv -f "$BP.aosp-ims-new" "$BP"; then
    ui_print "  build.prop: incoming-call handling back to the ROM's setting"
  fi
  rm -f "$BP.aosp-ims-new" "$SYS/etc/aosp-ims-incoming-calls.flipped"
fi
''', 1),
    ('rm -f "$PRODMNT/overlay/JoanImsPhoneDefault.apk"\n',
     'rm -f "$PRODMNT/overlay/ImsStackPhoneOverlay.apk"\n', 1),
    ('rm -f "$PRODMNT/overlay/JoanFwVolte.apk"\n',
     'rm -f "$PRODMNT/overlay/ImsStackFrameworkOverlay.apk"\n', 1),
]


def rewrite(src, rules, name):
    text = open(src).read()
    for old, new, count in rules:
        n = text.count(old)
        if n != count:
            raise SystemExit(f'{name}: expected {count}x {old[:60]!r}, found {n}')
        text = text.replace(old, new)
    # joan names that must not survive, outside the migration block and
    # the leftover cleanups that stay deliberately.
    allowed = ('priv-app/JoanIms"', 'JoanImsPhoneDefault.apk', 'JoanFwVolte.apk',
               'org.joan.ims.xml', 'joan-ims-ua', 'joan-ims.rc', 'joan-imsd.rc',
               'bin/joan-ims"', 'joan-grant', 'joan-orig', 'joan-added',
               'joan-merged', 'joan-new', 'joan-viettel', '/mnt/joan_')
    for line in text.splitlines():
        if line.lstrip().startswith('#'):
            continue
        stripped = line
        for a in allowed:
            stripped = stripped.replace(a, '')
        if 'JoanIms' in stripped or 'org.joan.ims' in stripped:
            raise SystemExit(f'{name}: joan name left in: {line.strip()}')
    head, rest = text.split('\n', 1)
    return head + '\n' + BANNER.format(src=name) + rest


def main(scripts, out):
    os.makedirs(out, exist_ok=True)
    for src, rules, dst in (('update-binary', INSTALL + FRESH, 'update-binary'),
                            ('update-binary', INSTALL + MIGRATE, 'update-binary-migrate'),
                            ('update-binary-cleanup', UNINSTALL, 'update-binary-cleanup')):
        text = rewrite(os.path.join(scripts, src), rules, src)
        path = os.path.join(out, dst)
        with open(path, 'w') as f:
            f.write(text)
        os.chmod(path, 0o755)
        print(f'wrote {path}')


if __name__ == '__main__':
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    main(*sys.argv[1:])
