#!/usr/bin/env python3
"""Carrier config for the AOSP IMS stack, as CarrierConfig vendor.xml blocks.

A source build splices one region, between the aosp-ims markers, into
joan-common's own vendor.xml (--splice; upstream/aosp-ims/apply-patches.sh
does this).

The flashable zip and the repacked ROM cannot: an overlay's vendor.xml
replaces the ROM's whole file, and a LineageOS-based ROM may ship its own.
They carry the imported blocks as app assets instead, one file per PLMN
(--assets), which CarrierImsGate applies at run time on top of whatever
the ROM ships, with the same rules as the region.

CarrierConfig applies every block whose filters match, in document order,
after the carrier's own config, so the region is ordered:

1. ePDG addresses from CarrierImsGate's table, by Android carrier id and
   PLMN through joan's maps, as the gate resolves a SIM. First, so that
2. the imported per-carrier IMS config (--imported: LineageOS's Pixel
   carrier settings, tools/import-carrier-settings.py) wins where it has
   an address of its own;
3. last, for every SIM: VoLTE and Wi-Fi calling offered, and the VoLTE
   toggle visible, editable and able to turn IMS off. The same rules
   CarrierImsGate applies at run time in the zip.

Video calling and RTT are left to each carrier's imported config: they
need the network's support, where VoLTE and Wi-Fi calling are offered to
every SIM and simply stay on LTE where the network has nothing.

Usage:
  make-carrier-config.py <carrier-id-map.json> <carrier-plmn-map.json>
      <CarrierImsGate.java> <carrier_list.textpb> [--imported <file>]
      [--splice <vendor.xml> | --full <base vendor.xml> | --assets <dir>]

Prints the region; --splice rewrites the given vendor.xml in place
(replacing an earlier region, or inserting before </carrier_config_list>);
--full prints the given base file with the region spliced in; --assets
writes the imported blocks to <dir>/<mcc><mnc>.xml, in their order.
"""
import json
import re
import sys
from xml.sax.saxutils import escape, quoteattr

BEGIN = '    <!-- aosp-ims-begin: generated by aosp-ims/tools/make-carrier-config.py -->'
END = '    <!-- aosp-ims-end -->'

KEY_VOLTE = 'carrier_volte_available_bool'
KEY_WFC = 'carrier_wfc_ims_available_bool'
KEY_HIDE_4G = 'hide_enhanced_4g_lte_bool'
KEY_EDITABLE_4G = 'editable_enhanced_4g_lte_bool'
KEY_ALLOW_TURNOFF_IMS = 'carrier_allow_turnoff_ims_bool'
KEY_EPDG_STATIC = 'iwlan.epdg_static_address_string'
KEY_EPDG_PRIORITY = 'iwlan.epdg_address_priority_int_array'
EPDG_ADDRESS_STATIC, EPDG_ADDRESS_PLMN = 0, 1

# The last block, for every SIM.
EVERY_SIM = [(KEY_VOLTE, True), (KEY_WFC, True), (KEY_HIDE_4G, False),
             (KEY_EDITABLE_4G, True), (KEY_ALLOW_TURNOFF_IMS, True)]


def operator_of(profile):
    """"OP.CC" of an LG profile key such as TMO.US.NAO (CarrierImsGate.operatorOf)."""
    parts = profile.split('.')
    return parts[0] + '.' + parts[1] if len(parts) >= 2 else profile


def epdg_map(gate_java):
    """EPDG_BY_OPERATOR, read out of CarrierImsGate.java."""
    src = open(gate_java, encoding='utf-8').read()
    m = re.search(r'EPDG_BY_OPERATOR\s*=\s*Map\.of\((.*?)\);', src, re.S)
    if not m:
        raise SystemExit(f'{gate_java}: EPDG_BY_OPERATOR not found')
    vals = re.findall(r'"([^"]*)"', m.group(1))
    if not vals or len(vals) % 2:
        raise SystemExit(f'{gate_java}: EPDG_BY_OPERATOR is not key/value pairs')
    return dict(zip(vals[0::2], vals[1::2]))


def carrier_list(textpb):
    """{carrier id: (name, parent id or None)} from carrier_list.textpb."""
    out = {}
    for block in re.split(r'\ncarrier_id \{', open(textpb, encoding='utf-8').read()):
        m = re.search(r'canonical_id: (\d+)', block)
        if not m:
            continue
        name = re.search(r'carrier_name: "([^"]*)"', block)
        parent = re.search(r'parent_canonical_id: (\d+)', block)
        out[int(m.group(1))] = (name.group(1) if name else '',
                                int(parent.group(1)) if parent else None)
    return out


def load(id_map, plmn_map, gate_java, textpb):
    return (json.load(open(id_map)), json.load(open(plmn_map)), epdg_map(gate_java),
            carrier_list(textpb))


def epdg_values(addr):
    return [(KEY_EPDG_STATIC, addr),
            (KEY_EPDG_PRIORITY, [EPDG_ADDRESS_STATIC, EPDG_ADDRESS_PLMN])]


def epdg_blocks(ids, plmns, epdg, carriers):
    """[(filter attrs, comment, [(key, value)])]: our ePDG addresses.

    Only carrier ids the gate can match: it reads getSimCarrierId(), while a
    vendor.xml cid filter also matches the specific carrier id, so specific
    ids (those with a parent in carrier_list.textpb) are left out.
    """
    out = []
    for plmn in sorted(plmns):
        addr = epdg.get(operator_of(plmns[plmn]))
        if addr:
            out.append(({'mcc': plmn[:3], 'mnc': plmn[3:]}, plmns[plmn], epdg_values(addr)))
    for cid in sorted(ids, key=int):
        name, parent = carriers.get(int(cid), ('', None))
        addr = epdg.get(operator_of(ids[cid]))
        if parent is not None or not addr:
            continue
        attrs = {'cid': cid}
        if name:
            attrs['name'] = name
        out.append((attrs, ids[cid], epdg_values(addr)))
    return out


def render_block(attrs, comment, values):
    head = ''.join(f' {k}={quoteattr(v)}' for k, v in attrs.items())
    lines = [f'    <carrier_config{head}> <!-- {escape(comment)} -->']
    for key, value in values:
        if isinstance(value, bool):
            lines.append(f'        <boolean name="{key}" value="{str(value).lower()}" />')
        elif isinstance(value, list):
            lines.append(f'        <int-array name="{key}" num="{len(value)}">')
            lines += [f'            <item value="{v}" />' for v in value]
            lines.append('        </int-array>')
        else:
            lines.append(f'        <string name="{key}">{escape(value)}</string>')
    lines.append('    </carrier_config>')
    return lines


def render(ids, plmns, epdg, carriers, imported=None):
    lines = [BEGIN,
             '    <!-- AOSP IMS stack (ImsStack). 1: ePDG addresses by carrier id and PLMN.',
             '         2: per-carrier IMS config imported from the Pixel carrier settings',
             '            LineageOS converts for Pixels (when present).',
             '         3: for every SIM, VoLTE and Wi-Fi calling offered, VoLTE toggle kept. -->']
    for attrs, comment, values in epdg_blocks(ids, plmns, epdg, carriers):
        lines += render_block(attrs, comment, values)
    if imported:
        lines.append(open(imported, encoding='utf-8').read().rstrip('\n'))
    lines += render_block({}, 'every SIM: VoLTE and Wi-Fi calling offered; the opt-out stays',
                          EVERY_SIM)
    lines.append(END)
    return '\n'.join(lines) + '\n'


def splice_text(doc, text):
    if BEGIN in doc:
        start = doc.index(BEGIN)
        end = doc.index(END, start) + len(END) + 1
        return doc[:start] + text + doc[end:]
    close = doc.rindex('</carrier_config_list>')
    return doc[:close].rstrip('\n') + '\n\n' + text + doc[close:]


def write_assets(imported, out_dir):
    """The imported blocks, one <carrier_config_list> file per PLMN."""
    import os
    import xml.etree.ElementTree as ET
    root = ET.fromstring('<l>' + open(imported, encoding='utf-8').read() + '</l>')
    by_plmn = {}
    for block in root.findall('carrier_config'):
        plmn = block.get('mcc', '') + block.get('mnc', '')
        if len(plmn) < 5 or not plmn.isdigit():
            raise SystemExit(f'{imported}: a block without mcc/mnc: {block.attrib}')
        block.tail = '\n'
        by_plmn.setdefault(plmn, []).append(ET.tostring(block, encoding='unicode'))
    os.makedirs(out_dir, exist_ok=True)
    for plmn, blocks in by_plmn.items():
        with open(os.path.join(out_dir, plmn + '.xml'), 'w', encoding='utf-8') as f:
            f.write('<?xml version="1.0" encoding="utf-8"?>\n<carrier_config_list>\n')
            f.write(''.join(blocks))
            f.write('</carrier_config_list>\n')
    print(f'{out_dir}: {len(by_plmn)} PLMN files, '
          f'{sum(len(b) for b in by_plmn.values())} blocks')


def main(argv):
    opts = {}
    for flag in ('--imported', '--splice', '--full', '--assets'):
        if flag in argv:
            i = argv.index(flag)
            opts[flag] = argv[i + 1]
            argv = argv[:i] + argv[i + 2:]
    if '--assets' in opts:
        if '--imported' not in opts:
            raise SystemExit('--assets needs --imported')
        write_assets(opts['--imported'], opts['--assets'])
        return
    if len(argv) != 4 or ('--splice' in opts and '--full' in opts):
        raise SystemExit(__doc__)
    ids, plmns, epdg, carriers = load(*argv)
    text = render(ids, plmns, epdg, carriers, opts.get('--imported'))
    if '--splice' in opts:
        path = opts['--splice']
        doc = splice_text(open(path, encoding='utf-8').read(), text)
        open(path, 'w', encoding='utf-8').write(doc)
        print(f'{path}: {text.count("<carrier_config")} carrier_config blocks in the region')
    elif '--full' in opts:
        sys.stdout.write(splice_text(open(opts['--full'], encoding='utf-8').read(), text))
    else:
        sys.stdout.write(text)


if __name__ == '__main__':
    main(sys.argv[1:])
