/* test_sip_units.c — host unit tests. Ground truth: pmOS builders that
 * achieved REGISTER 200 on 2026-08-26 (joan_ims_register.py etc).
 * AKA digest vectors below were generated by executing the proven
 * Python on this host (803db8…=qop path, 96dfc…=no-qop). */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "config.h"
#include "md5.h"
#include "secagree.h"
#include "sip.h"
#include "util.h"

static int g_fail;
#define CHECK(cond, name)                                              \
    do {                                                               \
        if (cond) {                                                    \
            printf("ok   %s\n", name);                                 \
        } else {                                                       \
            printf("FAIL %s\n", name);                                 \
            g_fail++;                                                  \
        }                                                              \
    } while (0)

static void test_md5(void)
{
    md5_ctx c;
    uint8_t d[16];
    char hex[33];

    md5_init(&c);
    md5_update(&c, "", 0);
    md5_final(&c, d);
    hex_encode(d, 16, hex, sizeof(hex));
    CHECK(!strcmp(hex, "d41d8cd98f00b204e9800998ecf8427e"), "md5 empty");

    md5_init(&c);
    md5_update(&c, "abc", 3);
    md5_final(&c, d);
    hex_encode(d, 16, hex, sizeof(hex));
    CHECK(!strcmp(hex, "900150983cd24fb0d6963f7d28e17f72"), "md5 abc");

    /* >64-byte input exercises block boundary */
    char big[200];
    memset(big, 'x', sizeof(big));
    md5_init(&c);
    for (size_t i = 0; i < sizeof(big); i++)
        md5_update(&c, big + i, 1);
    md5_final(&c, d);
    md5((const uint8_t *)big, sizeof(big), d);
    hex_encode(d, 16, hex, sizeof(hex));
    printf("     (block test hash=%s)\n", hex);
}

static void test_aka_vectors(void)
{
    uint8_t res[16];
    hex_decode("00112233445566778899aabbccddeeff", res, 16);

    char out33[33];
    aka_digest_response_hex(
        "user@msg.pc.t-mobile.com",
        "msg.pc.t-mobile.com",
        "REGISTER",
        "sip:msg.pc.t-mobile.com",
        "dGVzdG5vbmNlMTIzNA==",
        res, 16,
        "auth", "00000001", "cnonce01",
        out33);
    CHECK(!strcmp(out33, "803db8645c1631ba35e82bc29c8a26c3"),
          "aka digest qop=auth matches pmOS ground truth");

    aka_digest_response_hex(
        "user@msg.pc.t-mobile.com",
        "msg.pc.t-mobile.com",
        "REGISTER",
        "sip:msg.pc.t-mobile.com",
        "dGVzdG5vbmNlMTIzNA==",
        res, 16,
        NULL, NULL, NULL,
        out33);
    CHECK(!strcmp(out33, "96dfcc2174a9ee44d9aded7697ef9340"),
          "aka digest no-qop matches pmOS ground truth");

    /* 8-byte RES variant: digest must use exactly 8 bytes (no padding). */
    uint8_t res8[8];
    hex_decode("0011223344556677", res8, 8);
    aka_digest_response_hex(
        "user@msg.pc.t-mobile.com",
        "msg.pc.t-mobile.com",
        "REGISTER",
        "sip:msg.pc.t-mobile.com",
        "dGVzdG5vbmNlMTIzNA==",
        res8, 8,
        "auth", "00000001", "cnonce01",
        out33);
    CHECK(strcmp(out33, "803db8645c1631ba35e82bc29c8a26c3") != 0,
          "aka digest 8B RES differs from 16B (no silent padding)");
}

static void test_b64(void)
{
    uint8_t out[64];
    int n = b64_decode("dGVzdG5vbmNlMTIzNA==", out, sizeof(out));
    /* "testnonce1234" is 13 bytes. */
    CHECK(n == 13 && !memcmp(out, "testnonce1234", 13),
          "b64 decode basic");
}

static void test_sec_agree(void)
{
    sec_agree_t sa;
    int rc = sec_agree_parse(
        "ipsec-3gpp; alg=hmac-sha-1-96; ealg=aes-cbc; prot=esp; mod=trans; "
        "spi-c=300; spi-s=400; port-c=25000; port-s=26000",
        &sa);
    CHECK(rc == 0 && sa.spi_c == 300 && sa.spi_s == 400 &&
              sa.port_c == 25000 && sa.port_s == 26000,
          "sec-agree server parse");
    CHECK(!strcmp(sa.alg, "hmac-sha-1-96") && !strcmp(sa.ealg, "aes-cbc"),
          "sec-agree algs");

    rc = sec_agree_parse(
        "ipsec-3gpp; alg=hmac-sha-1-96; ealg=aes-cbc; spi-c=100; spi-s=200; "
        "port-c=15000; port-s=16000, ipsec-3gpp; alg=hmac-md5-96; ealg=aes-cbc; "
        "spi-c=101; spi-s=201; port-c=15001; port-s=16001",
        &sa);
    CHECK(rc == 0 && sa.spi_c == 100 && sa.port_s == 16000,
          "sec-agree comma list takes first");

    rc = sec_agree_parse("ipsec-3gpp; bogus=yes", &sa);
    CHECK(rc != 0, "sec-agree rejects missing fields");
}

static void sip_identity_t_maker(sip_identity_t *id)
{
    memset(id, 0, sizeof(*id));
    snprintf(id->impi, sizeof(id->impi), "%s",
             "user@msg.pc.t-mobile.com");
    snprintf(id->realm, sizeof(id->realm), "%s", "msg.pc.t-mobile.com");
    snprintf(id->local_ip, sizeof(id->local_ip), "%s", "2001:db8::2");
    id->local_port = 5060;
    snprintf(id->pcscf, sizeof(id->pcscf), "%s", "2001:db8::1");
    id->pcscf_port = 5060;
    snprintf(id->imei, sizeof(id->imei), "%.15s", "123456789012345");
    id->have_id = 1;
}

static void test_build_first(void)
{
    sip_identity_t id;
    sip_identity_t_maker(&id);
    sip_txn_t txn;
    sec_params_t mine = { .spi_c = 1111, .spi_s = 2222,
                          .port_c = 15000, .port_s = 16000 };
    txn_new(&txn, &id, mine);

    char msg[SIP_MAX_MSG];
    int n = build_register(msg, sizeof(msg), &id, &txn, 1, NULL,
                           NULL, 0, NULL, NULL);
    CHECK(n > 400 && n < SIP_MAX_MSG, "reg1 size sane");
    CHECK(strstr(msg,
                 "REGISTER sip:msg.pc.t-mobile.com SIP/2.0\r\n") != NULL,
          "reg1 request line");
    CHECK(strstr(msg, "From: <sip:user@msg.pc.t-mobile.com>;tag=") != NULL,
          "reg1 From/IMPU-aor+tag");
    CHECK(strstr(msg,
                 "Security-Client: ipsec-3gpp; alg=hmac-sha-1-96; "
                 "ealg=aes-cbc; prot=esp; mod=trans; spi-c=1111; spi-s=2222; "
                 "port-c=15000; port-s=16000,") != NULL,
          "reg1 Security-Client values");
    CHECK(strstr(msg, "Require: sec-agree") != NULL &&
              strstr(msg, "Proxy-Require: sec-agree") != NULL,
          "reg1 sec-agree requires");
    CHECK(strstr(msg,
                 "+g.3gpp.icsi-ref=\"urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel\"")
              != NULL,
          "reg1 mmtel icsi contact param");
    CHECK(strstr(msg, "Authorization: Digest username=\"user@msg.pc.t-mobile.com\"")
              != NULL,
          "reg1 empty digest has IMPI username");

    /* second REGISTER must reuse call-id/tag but new branch */
    char msg2[SIP_MAX_MSG];
    sip_challenge_t ch;
    memset(&ch, 0, sizeof(ch));
    snprintf(ch.nonce_b64, sizeof(ch.nonce_b64), "%s", "NONCEB64");
    ch.have_nonce = 1;
    snprintf(ch.algorithm, sizeof(ch.algorithm), "AKAv1-MD5");
    snprintf(ch.sec_server, sizeof(ch.sec_server), "%s",
             "ipsec-3gpp; alg=hmac-sha-1-96; ealg=aes-cbc; prot=esp; mod=trans; "
             "spi-c=300; spi-s=400; port-c=25000; port-s=26000");
    ch.have_sec_server = 1;

    uint8_t res[16];
    hex_decode("00112233445566778899aabbccddeeff", res, 16);
    build_register(msg2, sizeof(msg2), &id, &txn, 2, &ch, res, 16, res, res);
    CHECK(strstr(msg2, "Security-Verify:") != NULL, "reg2 Security-Verify present");
    {
        /* mk_branch runs on every build -> txn.branch IS reg2's branch. */
        const char *b = strstr(msg2, ";branch=");
        CHECK(b != NULL &&
              strncmp(b + 8, txn.branch, strlen(txn.branch)) == 0,
              "reg2 branch fresh");
        const char *b1 = strstr(msg, ";branch=");
        CHECK(b1 != NULL && strncmp(b1 + 8, txn.branch,
                                    strlen(txn.branch)) != 0,
              "reg2 branch differs from reg1");
    }
    CHECK(strstr(msg2, "CSeq: 2 REGISTER") != NULL, "reg2 cseq");
    CHECK(strstr(msg2, "integrity-protected=yes") != NULL,
          "reg2 integrity flag");
}

static void test_response_parse(void)
{
    static const char r401[] =
        "SIP/2.0 401 Unauthorized\r\n"
        "To: <sip:user@msg.pc.t-mobile.com>;tag=xyz\r\n"
        "WWW-Authenticate: Digest realm=\"msg.pc.t-mobile.com\", "
        "nonce=\"ABC=\", algorithm=AKAv1-MD5, qop=\"auth\"\r\n"
        "Security-Server: ipsec-3gpp; q=0.1; alg=hmac-sha-1-96; ealg=aes-cbc; "
        "spi-c=300; spi-s=400; port-c=25000; port-s=26000\r\n"
        "Content-Length: 0\r\n\r\n";
    sip_response_t rr;
    int rc = parse_response(r401, sizeof(r401) - 1, &rr);
    CHECK(rc == 0 && rr.status == 401, "parse 401 status");
    CHECK(rr.have_www_auth && strstr(rr.www_authenticate, "nonce=\"ABC=\""),
          "parse www-auth nonce extractable");
    CHECK(rr.have_sec_server, "parse security-server");
    CHECK(rr.expires == -1, "parse absent expires");
    CHECK(rr.session_expires == 0, "parse absent session-expires");

    static const char r200se[] =
        "SIP/2.0 200 OK\r\n"
        "Session-Expires: 90;refresher=uac\r\n"
        "Content-Length: 0\r\n\r\n";
    sip_response_t se;
    CHECK(parse_response(r200se, sizeof(r200se) - 1, &se) == 0 &&
          se.status == 200, "parse 200 with session-expires");
    CHECK(se.session_expires == 90, "parse session-expires 90");
    CHECK(!strcmp(se.se_refresher, "uac"), "parse refresher uac");
}

static void test_sdp_and_tcp_frame(void)
{
    static const char sdp[] =
        "INVITE sip:user@ims.example.net SIP/2.0\r\n"
        "Content-Type: application/sdp\r\n"
        "Content-Length: 120\r\n"
        "\r\n"
        "v=0\r\n"
        "o=- 1 1 IN IP6 2001:db8::1\r\n"
        "s=-\r\n"
        "c=IN IP6 2001:db8::9\r\n"
        "t=0 0\r\n"
        "m=audio 40000 RTP/AVP 0 96 101\r\n"
        "a=rtpmap:0 PCMU/8000\r\n"
        "a=rtcp-mux\r\n";
    sdp_media_t m;
    CHECK(sdp_parse_media(sdp, &m) == 0, "sdp parse finds c/m");
    CHECK(!strcmp(m.ip, "2001:db8::9"), "sdp parse IP6");
    CHECK(m.port == 40000, "sdp parse port");
    CHECK(m.have_pcmu == 1, "sdp parse PCMU");
    CHECK(m.pt == 0, "sdp parse pt 0");
    CHECK(m.have_rtcp_mux == 1, "sdp parse rtcp-mux");

    static const char sdp_rtcp[] =
        "v=0\r\n"
        "c=IN IP6 2001:db8::9\r\n"
        "m=audio 22900 RTP/AVP 0\r\n"
        "a=rtpmap:0 PCMU/8000\r\n"
        "a=rtcp:23000\r\n";
    sdp_media_t m2;
    CHECK(sdp_parse_media(sdp_rtcp, &m2) == 0, "sdp parse a=rtcp body");
    CHECK(m2.have_rtcp_mux == 0, "sdp parse no mux");
    CHECK(m2.rtcp_port == 23000, "sdp parse a=rtcp port");
    CHECK(m2.port == 22900, "sdp parse rtp port with a=rtcp");

    char ans[512];
    int n = sdp_answer(ans, sizeof(ans), "2001:db8::2", 40000, sdp);
    CHECK(n > 40, "sdp answer size");
    CHECK(strstr(ans, "RTP/AVP 0") != NULL, "sdp answer PCMU");
    CHECK(strstr(ans, "AMR-WB") == NULL, "sdp answer not AMR");
    CHECK(strstr(ans, "a=rtcp-mux") != NULL, "sdp answer rtcp-mux");
    CHECK(strstr(ans, "a=rtcp:40001") != NULL, "sdp answer rtcp port");

    sip_identity_t id;
    memset(&id, 0, sizeof(id));
    snprintf(id.impi, sizeof(id.impi), "%s", "user@ims.example.net");
    snprintf(id.impu, sizeof(id.impu), "%s", "sip:user@ims.example.net");
    snprintf(id.realm, sizeof(id.realm), "%s", "ims.example.net");
    snprintf(id.local_ip, sizeof(id.local_ip), "%s", "2001:db8::2");
    id.local_port = 15000;
    id.contact_port = 16000;
    snprintf(id.pcscf, sizeof(id.pcscf), "%s", "2001:db8::1");
    id.pcscf_port = 5060;
    snprintf(id.imei, sizeof(id.imei), "%s", "123456789012345");
    id.have_id = 1;
    sip_txn_t txn;
    sec_params_t mine = { .spi_c = 1, .spi_s = 2, .port_c = 15000, .port_s = 16000 };
    txn_new(&txn, &id, mine);
    char msg[SIP_MAX_MSG];
    build_register(msg, sizeof(msg), &id, &txn, 1, NULL, NULL, 0, NULL, NULL);
    CHECK(strstr(msg, ":16000>") != NULL, "REGISTER Contact uses contact_port");
    CHECK(strstr(msg, "Via: SIP/2.0/UDP [2001:db8::2]:15000") != NULL,
          "REGISTER Via uses local_port");

    sip_dialog_t dlg;
    char inv[SIP_MAX_MSG];
    int ni = build_invite(inv, sizeof(inv), &id, "tel:+15551212",
                          NULL, NULL, 40000, &dlg);
    CHECK(ni > 0, "invite builds");
    CHECK(strstr(inv, "a=rtcp-mux") != NULL, "invite SDP rtcp-mux");
    CHECK(strstr(inv, "a=rtcp:40001") != NULL, "invite SDP rtcp port");
    CHECK(strstr(inv, "Supported: replaces, timer") == NULL,
          "invite does not advertise timer");

    char upd[SIP_MAX_MSG];
    int nu = build_update(upd, sizeof(upd), &id, "sip:peer@ims.example.net",
                          "tel:+15551212", NULL, NULL, &dlg, "totag", 90);
    CHECK(nu > 0 && strstr(upd, "UPDATE ") == upd, "update builds");
    CHECK(strstr(upd, "Session-Expires: 90;refresher=uac") != NULL,
          "update carries session-expires");

    char buf[256];
    const char *wire =
        "OPTIONS sip:x SIP/2.0\r\nContent-Length: 0\r\n\r\nINVITE";
    size_t bl = strlen(wire);
    memcpy(buf, wire, bl);
    buf[bl] = '\0';
    char out[256];
    CHECK(sip_extract_one(buf, &bl, out, sizeof(out)) == 1, "tcp extract one");
    CHECK(strstr(out, "OPTIONS") == out, "tcp extract OPTIONS");
    CHECK(bl == 6 && !memcmp(buf, "INVITE", 6), "tcp extract remainder");
}

int main(void)
{
    test_md5();
    test_aka_vectors();
    test_b64();
    test_sec_agree();
    test_build_first();
    test_response_parse();
    test_sdp_and_tcp_frame();
    if (g_fail) {
        printf("\n%d TEST(S) FAILED\n", g_fail);
        return 1;
    }
    printf("\nALL HOST TESTS PASSED\n");
    return 0;
}
