/* test_sip_units.c — host unit tests. Ground truth: pmOS builders that
 * achieved REGISTER 200 on 2026-08-26 (joan_ims_register.py etc).
 * AKA digest vectors below were generated by executing the proven
 * Python on this host (803db8…=qop path, 96dfc…=no-qop). */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "config.h"
#include "md5.h"
#include "secagree.h"
#include "sip.h"
#include "util.h"

static int g_fail;
#define CHECK(cond, name)                                              \
    do {                                                               \
        if (cond) {                                                    \
            printf("ok   %s\n", name);                                 \
        } else {                                                       \
            printf("FAIL %s\n", name);                                 \
            g_fail++;                                                  \
        }                                                              \
    } while (0)

static void test_md5(void)
{
    md5_ctx c;
    uint8_t d[16];
    char hex[33];

    md5_init(&c);
    md5_update(&c, "", 0);
    md5_final(&c, d);
    hex_encode(d, 16, hex, sizeof(hex));
    CHECK(!strcmp(hex, "d41d8cd98f00b204e9800998ecf8427e"), "md5 empty");

    md5_init(&c);
    md5_update(&c, "abc", 3);
    md5_final(&c, d);
    hex_encode(d, 16, hex, sizeof(hex));
    CHECK(!strcmp(hex, "900150983cd24fb0d6963f7d28e17f72"), "md5 abc");

    /* >64-byte input exercises block boundary */
    char big[200];
    memset(big, 'x', sizeof(big));
    md5_init(&c);
    for (size_t i = 0; i < sizeof(big); i++)
        md5_update(&c, big + i, 1);
    md5_final(&c, d);
    md5((const uint8_t *)big, sizeof(big), d);
    hex_encode(d, 16, hex, sizeof(hex));
    printf("     (block test hash=%s)\n", hex);
}

static void test_aka_vectors(void)
{
    uint8_t res[16];
    hex_decode("00112233445566778899aabbccddeeff", res, 16);

    char out33[33];
    aka_digest_response_hex(
        "user@msg.pc.t-mobile.com",
        "msg.pc.t-mobile.com",
        "REGISTER",
        "sip:msg.pc.t-mobile.com",
        "dGVzdG5vbmNlMTIzNA==",
        res, 16,
        "auth", "00000001", "cnonce01",
        out33);
    CHECK(!strcmp(out33, "803db8645c1631ba35e82bc29c8a26c3"),
          "aka digest qop=auth matches pmOS ground truth");

    aka_digest_response_hex(
        "user@msg.pc.t-mobile.com",
        "msg.pc.t-mobile.com",
        "REGISTER",
        "sip:msg.pc.t-mobile.com",
        "dGVzdG5vbmNlMTIzNA==",
        res, 16,
        NULL, NULL, NULL,
        out33);
    CHECK(!strcmp(out33, "96dfcc2174a9ee44d9aded7697ef9340"),
          "aka digest no-qop matches pmOS ground truth");

    /* 8-byte RES variant: digest must use exactly 8 bytes (no padding). */
    uint8_t res8[8];
    hex_decode("0011223344556677", res8, 8);
    aka_digest_response_hex(
        "user@msg.pc.t-mobile.com",
        "msg.pc.t-mobile.com",
        "REGISTER",
        "sip:msg.pc.t-mobile.com",
        "dGVzdG5vbmNlMTIzNA==",
        res8, 8,
        "auth", "00000001", "cnonce01",
        out33);
    CHECK(strcmp(out33, "803db8645c1631ba35e82bc29c8a26c3") != 0,
          "aka digest 8B RES differs from 16B (no silent padding)");
}

static void test_b64(void)
{
    uint8_t out[64];
    int n = b64_decode("dGVzdG5vbmNlMTIzNA==", out, sizeof(out));
    /* "testnonce1234" is 13 bytes. */
    CHECK(n == 13 && !memcmp(out, "testnonce1234", 13),
          "b64 decode basic");
}

static void test_sec_agree(void)
{
    sec_agree_t sa;
    int rc = sec_agree_parse(
        "ipsec-3gpp; alg=hmac-sha-1-96; ealg=aes-cbc; prot=esp; mod=trans; "
        "spi-c=300; spi-s=400; port-c=25000; port-s=26000",
        &sa);
    CHECK(rc == 0 && sa.spi_c == 300 && sa.spi_s == 400 &&
              sa.port_c == 25000 && sa.port_s == 26000,
          "sec-agree server parse");
    CHECK(!strcmp(sa.alg, "hmac-sha-1-96") && !strcmp(sa.ealg, "aes-cbc"),
          "sec-agree algs");

    rc = sec_agree_parse(
        "ipsec-3gpp; alg=hmac-sha-1-96; ealg=aes-cbc; spi-c=100; spi-s=200; "
        "port-c=15000; port-s=16000, ipsec-3gpp; alg=hmac-md5-96; ealg=aes-cbc; "
        "spi-c=101; spi-s=201; port-c=15001; port-s=16001",
        &sa);
    CHECK(rc == 0 && sa.spi_c == 100 && sa.port_s == 16000,
          "sec-agree comma list takes first");

    rc = sec_agree_parse("ipsec-3gpp; bogus=yes", &sa);
    CHECK(rc != 0, "sec-agree rejects missing fields");
}

static void sip_identity_t_maker(sip_identity_t *id)
{
    memset(id, 0, sizeof(*id));
    snprintf(id->impi, sizeof(id->impi), "%s",
             "user@msg.pc.t-mobile.com");
    snprintf(id->realm, sizeof(id->realm), "%s", "msg.pc.t-mobile.com");
    snprintf(id->local_ip, sizeof(id->local_ip), "%s", "2001:db8::2");
    id->local_port = 5060;
    snprintf(id->pcscf, sizeof(id->pcscf), "%s", "2001:db8::1");
    id->pcscf_port = 5060;
    snprintf(id->imei, sizeof(id->imei), "%.15s", "123456789012345");
    id->have_id = 1;
}

static void test_build_first(void)
{
    sip_identity_t id;
    sip_identity_t_maker(&id);
    sip_txn_t txn;
    sec_params_t mine = { .spi_c = 1111, .spi_s = 2222,
                          .port_c = 15000, .port_s = 16000 };
    txn_new(&txn, &id, mine);

    char msg[SIP_MAX_MSG];
    int n = build_register(msg, sizeof(msg), &id, &txn, 1, NULL,
                           NULL, 0, NULL, NULL);
    CHECK(n > 400 && n < SIP_MAX_MSG, "reg1 size sane");
    CHECK(strstr(msg,
                 "REGISTER sip:msg.pc.t-mobile.com SIP/2.0\r\n") != NULL,
          "reg1 request line");
    CHECK(strstr(msg, "From: <sip:user@msg.pc.t-mobile.com>;tag=") != NULL,
          "reg1 From/IMPU-aor+tag");
    CHECK(strstr(msg,
                 "Security-Client: ipsec-3gpp; alg=hmac-sha-1-96; "
                 "ealg=aes-cbc; prot=esp; mod=trans; spi-c=1111; spi-s=2222; "
                 "port-c=15000; port-s=16000,") != NULL,
          "reg1 Security-Client values");
    CHECK(strstr(msg, "Require: sec-agree") != NULL &&
              strstr(msg, "Proxy-Require: sec-agree") != NULL,
          "reg1 sec-agree requires");
    CHECK(strstr(msg,
                 "+g.3gpp.icsi-ref=\"urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel\"")
              != NULL,
          "reg1 mmtel icsi contact param");
    CHECK(strstr(msg, "Authorization: Digest username=\"user@msg.pc.t-mobile.com\"")
              != NULL,
          "reg1 empty digest has IMPI username");

    /* second REGISTER must reuse call-id/tag but new branch */
    char msg2[SIP_MAX_MSG];
    sip_challenge_t ch;
    memset(&ch, 0, sizeof(ch));
    snprintf(ch.nonce_b64, sizeof(ch.nonce_b64), "%s", "NONCEB64");
    ch.have_nonce = 1;
    snprintf(ch.algorithm, sizeof(ch.algorithm), "AKAv1-MD5");
    snprintf(ch.sec_server, sizeof(ch.sec_server), "%s",
             "ipsec-3gpp; alg=hmac-sha-1-96; ealg=aes-cbc; prot=esp; mod=trans; "
             "spi-c=300; spi-s=400; port-c=25000; port-s=26000");
    ch.have_sec_server = 1;

    uint8_t res[16];
    hex_decode("00112233445566778899aabbccddeeff", res, 16);
    build_register(msg2, sizeof(msg2), &id, &txn, 2, &ch, res, 16, res, res);
    CHECK(strstr(msg2, "Security-Verify:") != NULL, "reg2 Security-Verify present");
    {
        /* mk_branch runs on every build -> txn.branch IS reg2's branch. */
        const char *b = strstr(msg2, ";branch=");
        CHECK(b != NULL &&
              strncmp(b + 8, txn.branch, strlen(txn.branch)) == 0,
              "reg2 branch fresh");
        const char *b1 = strstr(msg, ";branch=");
        CHECK(b1 != NULL && strncmp(b1 + 8, txn.branch,
                                    strlen(txn.branch)) != 0,
              "reg2 branch differs from reg1");
    }
    CHECK(strstr(msg2, "CSeq: 2 REGISTER") != NULL, "reg2 cseq");
    CHECK(strstr(msg2, "integrity-protected=yes") != NULL,
          "reg2 integrity flag");
}

static void test_response_parse(void)
{
    static const char r401[] =
        "SIP/2.0 401 Unauthorized\r\n"
        "To: <sip:user@msg.pc.t-mobile.com>;tag=xyz\r\n"
        "WWW-Authenticate: Digest realm=\"msg.pc.t-mobile.com\", "
        "nonce=\"ABC=\", algorithm=AKAv1-MD5, qop=\"auth\"\r\n"
        "Security-Server: ipsec-3gpp; q=0.1; alg=hmac-sha-1-96; ealg=aes-cbc; "
        "spi-c=300; spi-s=400; port-c=25000; port-s=26000\r\n"
        "Content-Length: 0\r\n\r\n";
    sip_response_t rr;
    int rc = parse_response(r401, sizeof(r401) - 1, &rr);
    CHECK(rc == 0 && rr.status == 401, "parse 401 status");
    CHECK(rr.have_www_auth && strstr(rr.www_authenticate, "nonce=\"ABC=\""),
          "parse www-auth nonce extractable");
    CHECK(rr.have_sec_server, "parse security-server");
    CHECK(rr.expires == -1, "parse absent expires");
    CHECK(rr.session_expires == 0, "parse absent session-expires");

    static const char r200se[] =
        "SIP/2.0 200 OK\r\n"
        "Session-Expires: 90;refresher=uac\r\n"
        "Content-Length: 0\r\n\r\n";
    sip_response_t se;
    CHECK(parse_response(r200se, sizeof(r200se) - 1, &se) == 0 &&
          se.status == 200, "parse 200 with session-expires");
    CHECK(se.session_expires == 90, "parse session-expires 90");
    CHECK(!strcmp(se.se_refresher, "uac"), "parse refresher uac");
}

static void test_sdp_and_tcp_frame(void)
{
    static const char sdp[] =
        "INVITE sip:user@ims.example.net SIP/2.0\r\n"
        "Content-Type: application/sdp\r\n"
        "Content-Length: 120\r\n"
        "\r\n"
        "v=0\r\n"
        "o=- 1 1 IN IP6 2001:db8::1\r\n"
        "s=-\r\n"
        "c=IN IP6 2001:db8::9\r\n"
        "t=0 0\r\n"
        "m=audio 40000 RTP/AVP 0 96 101\r\n"
        "a=rtpmap:0 PCMU/8000\r\n"
        "a=rtcp-mux\r\n";
    sdp_media_t m;
    CHECK(sdp_parse_media(sdp, &m) == 0, "sdp parse finds c/m");
    CHECK(!strcmp(m.ip, "2001:db8::9"), "sdp parse IP6");
    CHECK(m.port == 40000, "sdp parse port");
    CHECK(m.have_pcmu == 1, "sdp parse PCMU");
    CHECK(m.pt == 0, "sdp parse pt 0");
    CHECK(m.have_rtcp_mux == 1, "sdp parse rtcp-mux");

    static const char sdp_rtcp[] =
        "v=0\r\n"
        "c=IN IP6 2001:db8::9\r\n"
        "m=audio 22900 RTP/AVP 0\r\n"
        "a=rtpmap:0 PCMU/8000\r\n"
        "a=rtcp:23000\r\n";
    sdp_media_t m2;
    CHECK(sdp_parse_media(sdp_rtcp, &m2) == 0, "sdp parse a=rtcp body");
    CHECK(m2.have_rtcp_mux == 0, "sdp parse no mux");
    CHECK(m2.rtcp_port == 23000, "sdp parse a=rtcp port");
    CHECK(m2.port == 22900, "sdp parse rtp port with a=rtcp");

    char ans[512];
    int n = sdp_answer(ans, sizeof(ans), "2001:db8::2", 40000, sdp);
    CHECK(n > 40, "sdp answer size");
    CHECK(strstr(ans, "RTP/AVP 0") != NULL, "sdp answer PCMU");
    CHECK(strstr(ans, "AMR-WB") == NULL, "sdp answer not AMR");
    CHECK(strstr(ans, "a=rtcp-mux") != NULL, "sdp answer rtcp-mux");
    CHECK(strstr(ans, "a=rtcp:40001") != NULL, "sdp answer rtcp port");

    sip_identity_t id;
    memset(&id, 0, sizeof(id));
    snprintf(id.impi, sizeof(id.impi), "%s", "user@ims.example.net");
    snprintf(id.impu, sizeof(id.impu), "%s", "sip:user@ims.example.net");
    snprintf(id.realm, sizeof(id.realm), "%s", "ims.example.net");
    snprintf(id.local_ip, sizeof(id.local_ip), "%s", "2001:db8::2");
    id.local_port = 15000;
    id.contact_port = 16000;
    snprintf(id.pcscf, sizeof(id.pcscf), "%s", "2001:db8::1");
    id.pcscf_port = 5060;
    snprintf(id.imei, sizeof(id.imei), "%s", "123456789012345");
    id.have_id = 1;
    sip_txn_t txn;
    sec_params_t mine = { .spi_c = 1, .spi_s = 2, .port_c = 15000, .port_s = 16000 };
    txn_new(&txn, &id, mine);
    char msg[SIP_MAX_MSG];
    build_register(msg, sizeof(msg), &id, &txn, 1, NULL, NULL, 0, NULL, NULL);
    CHECK(strstr(msg, ":16000>") != NULL, "REGISTER Contact uses contact_port");
    CHECK(strstr(msg, "Via: SIP/2.0/UDP [2001:db8::2]:15000") != NULL,
          "REGISTER Via uses local_port");

    sip_dialog_t dlg;
    char inv[SIP_MAX_MSG];
    int ni = build_invite(inv, sizeof(inv), &id, "tel:+15551212",
                          NULL, NULL, 40000, &dlg);
    CHECK(ni > 0, "invite builds");
    CHECK(strstr(inv, "a=rtcp-mux") != NULL, "invite SDP rtcp-mux");
    CHECK(strstr(inv, "a=rtcp:40001") != NULL, "invite SDP rtcp port");
    CHECK(strstr(inv, "Supported: replaces, timer") == NULL,
          "invite does not advertise timer");

    char upd[SIP_MAX_MSG];
    int nu = build_update(upd, sizeof(upd), &id, "sip:peer@ims.example.net",
                          "tel:+15551212", NULL, NULL, &dlg, "totag", 90,
                          NULL, NULL);
    CHECK(nu > 0 && strstr(upd, "UPDATE ") == upd, "update builds");
    CHECK(strstr(upd, "Session-Expires: 90;refresher=uac") != NULL,
          "update carries session-expires");

    char buf[256];
    const char *wire =
        "OPTIONS sip:x SIP/2.0\r\nContent-Length: 0\r\n\r\nINVITE";
    size_t bl = strlen(wire);
    memcpy(buf, wire, bl);
    buf[bl] = '\0';
    char out[256];
    CHECK(sip_extract_one(buf, &bl, out, sizeof(out)) == 1, "tcp extract one");
    CHECK(strstr(out, "OPTIONS") == out, "tcp extract OPTIONS");
    CHECK(bl == 6 && !memcmp(buf, "INVITE", 6), "tcp extract remainder");
}

/* RFC 3261 12.1.2: the UAC route set is every Record-Route, reversed.
 * Regression for the ACK that never reached the far end: only the first
 * header was captured and it was left in received order, so the ACK was
 * addressed past our own P-CSCF. */
static void test_route_set(void)
{
    const char *multi =
        "SIP/2.0 200 OK\r\n"
        "Via: SIP/2.0/UDP [2001:db8::1]:1234;branch=z9hG4bKa\r\n"
        "Record-Route: <sip:far.example.net;lr>\r\n"
        "Record-Route: <sip:scscf.example.net;lr>\r\n"
        "Record-Route: <sip:pcscf.example.net;lr>\r\n"
        "Call-ID: abc123\r\n"
        "CSeq: 21 INVITE\r\n"
        "Content-Length: 0\r\n\r\n";
    sip_response_t r;
    CHECK(parse_response(multi, strlen(multi), &r) == 0, "route set parses");
    CHECK(r.record_route_n == 3, "route set counts every Record-Route");
    CHECK(strncmp(r.record_route, "<sip:pcscf.example.net;lr>", 26) == 0,
          "route set puts our P-CSCF on top");
    CHECK(strstr(r.record_route, "far.example.net") != NULL &&
          strstr(r.record_route, "pcscf.example.net") <
          strstr(r.record_route, "far.example.net"),
          "route set is reversed end to end");
    CHECK(r.cseq == 21 && !strcmp(r.cseq_method, "INVITE"),
          "response CSeq method parsed");
    CHECK(!strcmp(r.call_id, "abc123"), "response Call-ID parsed");

    /* One header may carry several comma-separated URIs. */
    const char *folded =
        "SIP/2.0 200 OK\r\n"
        "Record-Route: <sip:a.example.net;lr>, <sip:b.example.net;lr>\r\n"
        "CSeq: 2 INVITE\r\n"
        "Content-Length: 0\r\n\r\n";
    CHECK(parse_response(folded, strlen(folded), &r) == 0, "folded rr parses");
    CHECK(r.record_route_n == 2, "folded rr splits on commas");
    CHECK(strncmp(r.record_route, "<sip:b.example.net;lr>", 22) == 0,
          "folded rr is reversed");

    /* A single Record-Route must survive unchanged. */
    const char *one =
        "SIP/2.0 200 OK\r\n"
        "Record-Route: <sip:only.example.net;lr>\r\n"
        "CSeq: 3 INVITE\r\n"
        "Content-Length: 0\r\n\r\n";
    CHECK(parse_response(one, strlen(one), &r) == 0, "single rr parses");
    CHECK(r.record_route_n == 1 &&
          !strcmp(r.record_route, "<sip:only.example.net;lr>"),
          "single rr unchanged");

    const char *none =
        "SIP/2.0 200 OK\r\nCSeq: 4 INVITE\r\nContent-Length: 0\r\n\r\n";
    CHECK(parse_response(none, strlen(none), &r) == 0, "no rr parses");
    CHECK(!r.have_record_route && r.record_route_n == 0, "no rr reported");
}

/* RFC 3261 12.2.1.1: a dialog request carries the dialog's remote/local URI,
 * established by the 2xx. IMS rewrites the To URI in transit (tel: becomes
 * sip:...@ims.mnc...), so an ACK rebuilt from the dialled URI never matches
 * the dialog: the far end retransmits its 200 to timer H and hangs up. */
static void test_ack_echoes_dialog_uris(void)
{
    sip_identity_t id;
    sip_identity_t_maker(&id);
    sip_dialog_t dlg;
    memset(&dlg, 0, sizeof(dlg));
    snprintf(dlg.call_id, sizeof(dlg.call_id), "callid-1");
    snprintf(dlg.from_tag, sizeof(dlg.from_tag), "fromtag1");
    dlg.cseq = 1;

    const char *to_hdr = "<sip:+15550001111@ims.mnc260.mcc310.3gppnetwork.org>;tag=farend9";
    const char *from_hdr = "<sip:user@msg.pc.t-mobile.com>;tag=fromtag1";

    char ack[SIP_MAX_MSG];
    int n = build_ack(ack, sizeof(ack), &id,
                      "sip:sbc.example.net", "tel:+15550001111",
                      "<sip:pcscf.example.net;lr>", "", &dlg, "farend9",
                      to_hdr, from_hdr);
    CHECK(n > 0, "ack builds");
    CHECK(strstr(ack, "ACK sip:sbc.example.net SIP/2.0\r\n") != NULL,
          "ack request-uri is the 2xx Contact");
    CHECK(strstr(ack,
                 "To: <sip:+15550001111@ims.mnc260.mcc310.3gppnetwork.org>"
                 ";tag=farend9\r\n") != NULL,
          "ack echoes the rewritten To verbatim");
    CHECK(strstr(ack, "To: <tel:+15550001111>") == NULL,
          "ack does not rebuild To from the dialled URI");
    CHECK(strstr(ack, "From: <sip:user@msg.pc.t-mobile.com>;tag=fromtag1\r\n")
          != NULL, "ack echoes From verbatim");
    CHECK(strstr(ack, "CSeq: 1 ACK\r\n") != NULL, "ack reuses INVITE CSeq");

    /* Without the response headers it must still build a usable ACK. */
    n = build_ack(ack, sizeof(ack), &id, "sip:sbc.example.net",
                  "tel:+15550001111", "", "", &dlg, "farend9", NULL, NULL);
    CHECK(n > 0 && strstr(ack, "To: <tel:+15550001111>;tag=farend9\r\n") != NULL,
          "ack falls back to dialled URI when 2xx headers absent");
}

/* A BYE that rebuilt To/From from the dialled URI was answered
 * 481 Call/Transaction Does Not Exist by Google Voice (measured), leaving
 * the far end's leg up. Same defect the ACK had. */
static void test_bye_echoes_dialog_uris(void)
{
    sip_identity_t id;
    sip_identity_t_maker(&id);
    sip_dialog_t dlg;
    memset(&dlg, 0, sizeof(dlg));
    snprintf(dlg.call_id, sizeof(dlg.call_id), "callid-2");
    snprintf(dlg.from_tag, sizeof(dlg.from_tag), "fromtag2");
    dlg.cseq = 1;

    const char *to_hdr = "<tel:+15550001111>;tag=farend7";
    const char *from_hdr = "\"Joan\" <sip:user@msg.pc.t-mobile.com>;tag=fromtag2";

    char bye[SIP_MAX_MSG];
    int n = build_bye(bye, sizeof(bye), &id, "sip:sbc.example.net",
                      "tel:+15550001111", "", "", &dlg, "farend7",
                      to_hdr, from_hdr);
    CHECK(n > 0, "bye builds");
    CHECK(strstr(bye, "To: <tel:+15550001111>;tag=farend7\r\n") != NULL,
          "bye echoes To verbatim");
    CHECK(strstr(bye, "From: \"Joan\" <sip:user@msg.pc.t-mobile.com>"
                      ";tag=fromtag2\r\n") != NULL,
          "bye keeps a display name the rebuild would have dropped");
    CHECK(strstr(bye, "CSeq: 2 BYE\r\n") != NULL, "bye increments CSeq");

    n = build_bye(bye, sizeof(bye), &id, "sip:sbc.example.net",
                  "tel:+15550001111", "", "", &dlg, "farend7", NULL, NULL);
    CHECK(n > 0 && strstr(bye, "To: <tel:+15550001111>;tag=farend7\r\n") != NULL,
          "bye falls back when dialog headers absent");

    /* RFC 3261 puts no upper bound on a To-tag. Google Voice via T-Mobile
     * returns 81 characters; a 64-byte tag buffer truncated that to 63 and
     * the far end could no longer match the dialog. */
    char longtag[82];
    memset(longtag, 'a', sizeof(longtag) - 1);
    longtag[sizeof(longtag) - 1] = '\0';
    CHECK(strlen(longtag) == 81, "81-char tag fixture");
    n = build_bye(bye, sizeof(bye), &id, "sip:sbc.example.net",
                  "tel:+15550001111", "", "", &dlg, longtag, NULL, NULL);
    CHECK(n > 0 && strstr(bye, longtag) != NULL,
          "an 81-char To-tag survives intact");
}

/* The IMS PDN advertises several P-CSCF addresses. Keeping only the first
 * left registration stuck on a drained node for 45 minutes. */
static void test_pcscf_candidates(void)
{
    ua_config_t c;
    cfg_init(&c);
    CHECK(cfg_apply_line(&c,
              "PCSCF=fd00:976a:b699:4901::5,fd00:976a:2:242::5,"
              "fd00:976a:2:2a1::6") == 0,
          "pcscf list applies");
    CHECK(c.pcscf_n == 3, "pcscf list keeps every candidate");
    CHECK(!strcmp(c.pcscf_list[0].addr, "fd00:976a:b699:4901::5") &&
          !strcmp(c.pcscf_list[2].addr, "fd00:976a:2:2a1::6"),
          "pcscf list preserves order");
    CHECK(!strcmp(c.id.pcscf, "fd00:976a:b699:4901::5"),
          "pcscf active is the first candidate");
    CHECK(c.pcscf_list[0].blocked_until_ms == 0, "pcscf starts unblocked");

    /* Spaces after commas are common in header-ish input. */
    cfg_init(&c);
    CHECK(cfg_apply_line(&c, "PCSCF=fd00::1, fd00::2") == 0,
          "pcscf spaced list applies");
    CHECK(c.pcscf_n == 2 && !strcmp(c.pcscf_list[1].addr, "fd00::2"),
          "pcscf list tolerates spaces");

    /* A single address must still work: older callers send exactly this. */
    cfg_init(&c);
    CHECK(cfg_apply_line(&c, "PCSCF=fd00:976a:b699:4901::5") == 0,
          "pcscf single applies");
    CHECK(c.pcscf_n == 1 &&
          !strcmp(c.id.pcscf, "fd00:976a:b699:4901::5"),
          "pcscf single address unchanged");
}

int main(void)
{
    test_md5();
    test_aka_vectors();
    test_b64();
    test_sec_agree();
    test_build_first();
    test_response_parse();
    test_sdp_and_tcp_frame();
    test_route_set();
    test_ack_echoes_dialog_uris();
    test_bye_echoes_dialog_uris();
    test_pcscf_candidates();
    if (g_fail) {
        printf("\n%d TEST(S) FAILED\n", g_fail);
        return 1;
    }
    printf("\nALL HOST TESTS PASSED\n");
    return 0;
}
